hidden_size: 32
mu_scale: Null
rho_scale: -5
sigma1: 1
sigma2: 0.002
pi: 0.5
verbose: True
lr: 0.005
num_epochs: 1000
dropout: 0.5
n_samples_train: 10
n_samples_test: 100
batch_size: 32
early_stop: True
patience: 50